mutation globalDescriptorUpsertMutation($input: GlobalDescriptorUpsertInput!) {
  globalDescriptorUpsert(input: $input) {
    errors {
      ... on MutationError {
        __typename
        message
        field
      }
    }
    job {
      id
      completedAt
      descriptors {
        totalCount
        edges {
          node {
            descriptor
            id
          }
        }
      }
      errors {
        totalCount
        edges {
          node {
            name
            message
            isFatal
          }
        }
      }
    }
  }
}
