query ($first: Int, $after: ID) {
  viewer {
    name
    organizationUsers {
      edges {
        node {
          organization {
            id
            name
            description
            email
            website
            studies(first: $first, after: $after) {
              edges {
                node {
                  id
                  globalId
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
