query jobdesc($id: ID!) {
node(id: $id) {
    ...on Job {
      createdAt
      completedAt
      operation
      ... on JobFhirResourceIngest {
        fhirResourceAggregation {
          resourceType
          count
        }
      }
      errors(first: 10) {
        edges {
          node {
            id
            name
            message
          }
        }
      }
    }
  }
}
