query orgStudies($id: ID!, $first: Int, $after: ID) {
  node(id: $id) {
    id
    ... on Organization {
      name
      id
      studies(first: $first, after: $after) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        edges {
          cursor
          node {
            id
            globalId
            name
          }
        }
      }
    }
  }
}
